src/App.js

this is my first sample test PR for issue #4.

Add my sample text to app.js

---

src/App.js

Feature initial pr #4 yordan

---

src/App.js

Name added as requested by PM. And a little OCD formatting.

added name as part of initial PR

---

src/app/index.js

hello world, how are you?

---

src/app/index.js

hello world, again?

---

src/app/index.js

goodbye world. yay

---

src/app/index.js

added random text to index.js to test

---

src/app/pages/LandingPage.js

add pages directory and landing page

---

src/app/layouts/PrimaryLayout.js

add layouts directory & PrimaryLayout

---

package-lock.json
package.json
src/app/components/Navbar/Navbar.js

32 feat react router

---

src/app/pages/LandingPage.js

55 feat add slide header to LP

---

src/app/pages/SignUp.js

add temp h1 to sign up page

---

src/app/pages/BookGrill.js

add h1 to Book a grill page

---

src/app/pages/Pricing.js

add h1 to pricing page

---

src/app/pages/HowToGrill.js

add h1 to how to grill page

---

src/app/layouts/PrimaryLayout.js

53 feat add routes to primary layout

---

src/app/index.js

54 feat browser router

---

src/app/components/Footer/Footer.css
src/app/components/Footer/Footer.js

fixed issue #62

---

src/app/components/Card/Card.js

67 feat card

---

src/app/components/HowItWorks/styles.css

74 style media query

---

src/app/components/HowItWorks/styles.css

77 style colors

---

src/app/components/Navbar/styles.css

position relative to .nav

---

src/app/components/HowItWorks/HowItWorks.js
src/app/components/HowItWorks/styles.css

81 add link to <HowItWorks />

---

src/app/components/HowItWorks/styles.css
src/app/components/Navbar/styles.css
src/index.css

83 base style <a>

---

src/app/components/HowItWorks/styles.css

change card h3 font in <HowItWorks />

---

src/app/pages/BookGrill.js
src/app/pages/HowToGrill.js
src/app/pages/LandingPage.js
src/app/pages/Pricing.js
src/app/pages/SignUp.js

change div to main tag in pages/

---

package-lock.json
package.json
src/App.js
src/app/components/Card/Card.js
src/app/components/Footer/Footer.css
src/app/components/Footer/Footer.js
src/app/components/HowItWorks/HowItWorks.js
src/app/components/HowItWorks/styles.css
src/app/components/Navbar/Navbar.js
src/app/components/PrettierTest/PrettyTest.js
src/app/components/SlideHeader/SlideHeader.js
src/app/components/SlideHeader/carousel.css
src/app/components/SlideHeader/carousel.scss
src/app/components/WhatIsGrillber/WhatIs.js
src/app/components/WhatIsGrillber/styles.css
src/app/components/WhatIsGrillber/styles.scss
src/app/index.js
src/app/layouts/PrimaryLayout.js
src/app/pages/BookGrill.js
src/app/pages/HowToGrill.js
src/app/pages/LandingPage.js
src/app/pages/Pricing.js
src/app/pages/SignUp.js
src/index.css
src/index.js

adds prettier, husky, lint-staged for precommit hook

---

src/app/components/HowItWorks/HowItWorks.js
src/app/components/HowItWorks/styles.css

changes h2 to h1 in header HowItWorks

---

src/app/components/SlideHeader/carousel.css
src/app/components/SlideHeader/carousel.scss

fixed issues with slider images not fitting the window

---

src/app/components/HowItWorks/styles.css
src/app/styles/cta-buttons.css

add .cta-join to separate file in styles/, delete in local css

---

src/app/pages/LandingPage.js

104 feat import landing

---

src/app/components/Reviews/Reviews.css
src/app/components/Reviews/Reviews.js

closes #109
Corrected height issue. Also did a tiny bit of housekeeping- outer div element re-labeled to <section> and change of color to contrast HIW component.

109 reviews height

---

src/app/components/SlideHeader/carousel.css

closes #114 
Added opaque bg to slider

114 add opaque bg slider

---

src/app/components/SlideHeader/SlideHeader.js
src/app/components/SlideHeader/carousel.css

closes #96 
Added join button to slider

changed slider button to 'join'

---

src/app/components/Navbar/Navbar.js

change brand to Grillber in Navbar

---

src/app/styles/cta-buttons.css

118 style opacity join

---

src/app/components/SubHeader/styles.css

changed h2 font weight to normal

---

src/app/components/WhatIsGrillber/styles.css
src/app/components/WhatIsGrillber/styles.scss

media queries for font size ul

---

src/app/pages/HowToGrill.js

#126 features creating h2

---

client/src/app/components/Card/Card.js
client/src/app/components/Card/styles.css
client/src/app/components/HowItWorks/HowItWorks.js
client/src/app/components/HowItWorks/styles.css

137 style card default

---

client/package-lock.json
client/package.json

add express server & use cross-env to change port 4000

---

.babelrc
client/package.json
client/src/app/pages/Pricing.js
package-lock.json
package.json
server.js

add server babel config

---

client/src/app/components/Footer/Footer.js

add key property to elements in Footer

---

client/src/app/components/Navbar/styles.css

Fixed position of the button

---

client/src/app/components/Input/Input.js
client/src/app/components/Input/styles.css

add input componet

---

client/src/app/pages/SignUp.js
client/src/app/styles/cta-buttons.css

Form to sign up page. 

---

.gitignore
package-lock.json
package.json
test/connection.js
test/finding_db.js
test/mongo.js
test/saving_db.js

166 feat mocha mongo

---

.babelrc
package-lock.json
package.json
server/graphql/Resolvers/resolvers.js
server/graphql/schema.js
server/graphql/typeDefs/typeDefs.js
server/server.js

closes #168 . 
adds apollo server and resolver for all users from mongo db.

168 feat apollo server

---

server/models/Grill.js
server/server.js

171 feat grill model

---

server/graphql/typeDefs/typeDefs.js

adds grill schema graphql

---

server/graphql/Resolvers/resolvers.js

add grill graphql resolver

---

client/src/app/pages/Pricing.js
server/server.js

 closes issue 174

---

server/graphql/Resolvers/resolvers.js
server/graphql/typeDefs/typeDefs.js
server/server.js

179. resolver by grill(name)

---

server/graphql/Resolvers/resolvers.js
server/graphql/typeDefs/typeDefs.js

170 feat mutation create user

---

client/src/app/components/Loader/Loader.css
client/src/app/components/Loader/Loader.js
client/src/app/pages/Pricing.js

154-feat-spinnerLoader

---

client/src/app/components/FAQ/Faq.js
client/src/app/components/FAQ/styles.css

185 feat faq pricing

---

server/graphql/Resolvers/resolvers.js
server/graphql/typeDefs/typeDefs.js

183 resolver to find user by _id

---

client/src/app/index.js

add apollo client and provider to app component

---

package-lock.json
package.json

uninstall react apollo on server

---

server/graphql/Resolvers/resolvers.js
server/graphql/typeDefs/typeDefs.js

closes #196  also fixes the resolver to resolve by _id.

196 feat query grill

---

client/package.json

install prop-types package

---

client/src/app/components/SlideHeader/SlideHeader.js

202 feat prop types slide header

---

client/src/app/components/Loader/Loader.js

add prop types to Loader

---

client/src/app/components/FAQ/Faq.js

refactor return statement in faqs

---

client/src/app/components/SlideHeader/SlideHeader.js
client/src/app/components/SlideHeader/carousel.css
client/src/app/components/SlideHeader/carousel.scss
client/src/app/pages/HowToGrill/HowToGrill.js

closes #208. 
This is the how it is now.

208 bug slide header iphone5

---

server/graphql/typeDefs/typeDefs.js
server/models/Grill.js

212 feat price grill models & gql schema

---

client/src/app/components/SubHeader/SubHeader.js

200 feat prop types sub header

---

client/src/app/components/Grill/Grill.js
client/src/app/components/Grill/styles.css
client/src/app/components/GrillList/GrillList.js
client/src/app/components/GrillList/styles.css
client/src/app/pages/BookGrill.js

added Grill and GrillList components

---

client/src/app/graphql/queries.js

226 feat apollo queries for Grills & Create User

---

client/src/app/layouts/PrimaryLayout.js

add exact to routes in primaryLayout

---

client/src/app/components/UserForm/UserForm.js
client/src/app/pages/SignUp.js

236 feat mutation user form

---

client/src/app/components/UserForm/UserForm.js
client/src/app/layouts/PrimaryLayout.js
client/src/app/pages/ThankYouUser.js

238 feat redirect on submit

---

client/src/app/components/Grill/Grill/styles.css

fix style bug by specifying classes

---

client/src/app/index.js
client/src/app/layouts/PrimaryLayout.js

250 chore fragments

---

client/src/app/components/Grill/Grill/Grill.js

add alt tag to grill images

---

client/src/app/pages/Pricing.js

added components in pricing page
closes #225

added: SubHeader, Price, FAQ components to Pricing Page

---

client/src/app/components/Grill/GrillList.js
client/src/app/components/Grill/Grill_Item/Grill_Item.js
client/src/app/pages/Pricing.js

256 chore console grill pricing

---

server/graphql/typeDefs/typeDefs.js
server/models/User.js

258 chore fix type String: user model mobile_number

---

client/package-lock.json
client/package.json
client/src/app/components/UserForm/UserForm.js

260 refactor userForm to use Formik

---

client/src/app/components/UserForm/UserForm.js
client/src/app/pages/SignUp.js

262 feat redirect to ThankYouUser on form submit

---

server/server.js

add error function for mongoose.connect()

---

client/src/app/components/Card/Card.js
server/helper.js

#241: Card propTypes added

---

client/src/app/components/Navbar/Navbar.js

271 feat close nav menu

---

client/src/app/components/UserForm/UserForm.js

change mobile number placeholder

---

client/src/app/components/UserForm/UserForm.js

276 bugs: typo on prop & phone regex --userForm

---

client/src/app/pages/BookGrill.js

Loader added in the Grill page

---

client/src/app/pages/Pricing.js

269-Pricing page "margin-top" added

---

client/src/app/pages/SignUp.js

Centered "Terms" tag

---

client/src/app/layouts/PrimaryLayout.js

fix typo for noMatch route in primaryLayout

---

client/src/app/components/Grill/Grill_Item/Grill_Item.js
client/src/app/layouts/PrimaryLayout.js
client/src/app/pages/SingleGrill.js

286 feat grill detail page route

---

client/src/app/components/Grill/Grill_Item/Grill_Item.js

add key property to star <i /> in <GrillItem />

---

client/src/app/components/Grill/Grill_Item/styles.css

style: flex direction, list style image, margin left to features list

---

client/src/app/components/Grill/Grill_Item/Grill_Item.js
client/src/app/components/Grill/Grill_Item/styles.css

293 refactor classnames grill item

---

client/src/app/components/Grill/Grill_Item/Grill_Item.js
client/src/app/components/Grill/Grill_Item/styles.css

295 adjust styles a bit in <GrillItem />

---

client/src/app/components/Stars/Stars.js
client/src/app/components/Stars/styles.css

297 feat stars

---

server/graphql/typeDefs/typeDefs.js
server/models/Grill.js

301 add allImages data field to schema & model

---

client/src/app/components/Stars/Stars.js
client/src/app/components/Stars/styles.css

303 refactor stars fill in

---

client/src/app/components/Grill/Grill_Item/Grill_Item.js
client/src/app/components/Grill/Grill_Item/styles.css
client/src/app/components/Reviews/Reviews.css
client/src/app/components/Reviews/Reviews.js

299 refactor components with stars

---

client/src/app/components/Panel/Panel.js
client/src/app/components/Panel/styles.css

298 feat panel

---

client/src/app/components/Panel/styles.css

font family to indie flower in <Panel />

---

client/src/app/components/Grill/GrillDetail/GrillDetail.js
client/src/app/components/Grill/GrillDetail/styles.css
package-lock.json
package.json

311 feat grill detail

---

client/src/app/components/Grill/GrillDetail/GrillDetail.js
client/src/app/pages/SingleGrill/SingleGrill.js

316 & 318 minor bugs grilldetail & singleGrill

---

package-lock.json
package.json

322 chore npm server

---

server/auth/auth.js

326 feat token utilities

---

server/graphql/Resolvers/resolvers.js

328 feat resolvers tokens

---

client/package-lock.json
client/package.json
client/src/app/auth/auth.js

333 feat auth client

---

client/src/app/auth/auth.js
server/server.js

339 bugs auth server

---

client/src/app/components/Navbar/Navbar.js
client/src/app/layouts/GrillLayout.js
client/src/app/layouts/PrimaryLayout.js

335 feat grill layout

---

client/src/app/components/Login/Login.js
client/src/app/components/Login/styles.css

add Login Form with styles

---

server/graphql/Resolvers/resolvers.js

345 bugs resolver create user

---

client/src/app/auth/auth.js
client/src/app/components/Navbar/Navbar.js

348 feat navbar logout

---

client/src/app/components/Footer/Footer.css
client/src/app/components/Footer/Footer.js

351 feat chingu GitHub footer

---

client/src/app/components/NoFound/NoFound.js

change pageLink & path in Card props

---

client/src/app/components/Navbar/Navbar.js

add / in front of auth/book-a-grill link

---

client/package-lock.json
client/src/app/components/Reviews/Reviews.css

style: justify content center, background url https

---

client/src/app/styles/cta-buttons.css

add styles to cta-sign-up span

---

client/package-lock.json
client/package.json

362 feat client npm heroku

---

package.json
server/index.js

366 bug server
